### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by SzotsGabor** [archishou/MidnightChessEngine#5]
Hi, 

Will v5 not be released? I see it does not have a version number in its id.

Gabor Szots
CCRL testing group

**Comment by archishou** [comment]
If the question is about uci I don't really like having the version number in the name. It can be changed if required but thats why its not there as of now

**Comment by SzotsGabor** [comment]
> If the question is about uci I don't really like having the version number in the name. It can be changed if required but thats why its not there as of now

Yes, UCI. For testers it is easier to have it in the name to avoid confusion when several versions are ttested. And in version v4 you put it in the name although it says it is v3. Then maybe it is indeed better not to include it in the id.

**Comment by archishou** [comment]
Release has been updated with the version number in uci id. Please let me know if there are any other issues.

**Comment by SzotsGabor** [comment]
Thanks.
I have an ongoing tournament. If the only change is the version number then I'll replace the old exe with the new one.

**Comment by archishou** [comment]
Yep only change is version number added to uci

**Comment by SzotsGabor** [comment]
Version 8 displays wrong version number (7).
