### ISSUE TITLE
v8 smaller file ?

### ISSUE THREAD

**Issue by tissatussa** [archishou/MidnightChessEngine#73]
i copied your source code by `git clone` and after a successfull `make` i get a binary of only 813.6 Kb, which is rather small compared to my previous compilations of v7 and v8 (being around 3 Mb). Is it because of the new net M004 ? Is it embedded into the binary ? (i guess so)

**Comment by archishou** [comment]
No, this is because my attack tables for move generation are no longer done at compile time because it used to take very long. Now it's done at run time which means smaller binaries and faster build times :)
